name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.13"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') \
        # Missing Module Docstring
        --disable C0114 \
        # Missing Class Docstring
        --disable C0115 \
        # Missing Function Docstring
        --disable C0116 \
        # Instance of .. has no .. member
        --disable E1101 \
        # Unable to import ..
        --disable E0401 \
        --fail-under 7.0 \
        --ignore-paths ^ml-model/yolov5/.*$
